import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import styles from '@/styles/Hero.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Hero() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center} style={{margin:'auto'}}>
          <h1>Bill</h1>
        </div>

        <div className={styles.grid}>
          <Link
            href="/1"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Home <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </Link>

          <Link href="/learn" className={styles.card}>
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Stay up to date with new bills&nbsp;!
            </p>
          </Link>

          <Link
            href="/contact"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Contact <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Stay up to date with new bills&nbsp;!
            </p>
          </Link>
        </div>
      </main>
    </>
  )
}
