import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import styles from '@/styles/Hero.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Hero() {
  return (
    <a href="/1">
      <section className="bg-gradient-to-r from-blue-100 via-blue-300 to-blue-500 flex min-h-screen">
      <Head>
        <title>De Brief - Everything about Texas Legislation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/" />
      </Head>

      <main className={styles.main + ' mx-auto'}>
        <div className="justify-center flex-auto mt-10">
          <Image src='/logo.svg' alt="De Brief" width={1000} height={800}></Image>
          <div className="text-5xl font-bold text-gray-700 dark:text-gray-400 ml-40 text-end"> Where Everyone Participates. </div> 
        </div>
      </main>
    </section>
    </a>

  )
}
